settings:
  verbose: 1 # 0: minimal, 1: GA plot & basic info, 2: data heads
  run_ga_for_pca: True # True to use GA for PCA, False to use manual PCA settings or no PCA

data_loader:
  data_folder_path: "data"
  specific_file: "Dati_wallbox_aggregati.csv" 
  # If specific_file is null or commented out, it will load all CSVs.

preprocessing:
  scaler: "StandardScaler" # Options: "StandardScaler", "MinMaxScaler", None

# Bayesian Feature Selection Configuration
bayesian_feature_selection:
  enabled: True                    # Enable/disable Bayesian feature selection
  use_optimized: True              # Use optimized version for high-dimensional data
  max_parents: 2                   # Maximum number of parents per node (reduced for speed)
  scoring_method: "bic"            # Scoring method: "bic" or "k2"
  target_variable: null            # Target variable name (if any) to focus selection around
  min_features: 15                 # Minimum number of features to select
  max_features: 40                 # Maximum number of features to select
  visualize_network: True          # Whether to visualize the Bayesian network
  save_feature_ranking: True       # Whether to save detailed feature ranking to CSV
  
  # Optimization parameters for high-dimensional data
  optimization:
    max_features_for_bn: 50        # Pre-filter to this many features before BN learning
    prefilter_method: "correlation" # Pre-filtering method: "correlation", "variance", "pairwise_mi"
    prefilter_threshold: 0.1       # Threshold for pre-filtering
    max_iter: 30                   # Maximum iterations for Hill Climbing (reduced for speed)
    skip_parameter_learning: True   # Skip CPD estimation for speed (structure analysis only)

pca:
  # Manual PCA settings (used if run_ga_for_pca is False and manual_pca_components > 0)
  manual_pca_components: 0.85 # Number of PCA components. 0 means no PCA if GA is off.
                           # Can also be a float between 0 and 1 (e.g., 0.95 for 95% variance)

genetic_pca_optimizer:
  # Only used if settings.run_ga_for_pca is True
  params:
    population_size: 30
    generations: 20
    crossover_prob: 0.7
    mutation_prob: 0.2
    # Fitness weights
    silhouette_weight: 0.8       # Weight for Silhouette Score
    components_penalty_weight: 0.2 # Penalty for number of PCA components (to encourage fewer)
    # Range of PCA components for GA to explore (0 means no PCA)
    min_pca_components_ratio: 0.1 # Min ratio of original features (0 = no PCA allowed in search)
    max_pca_components_ratio: 0.7 # Max ratio of original features (e.g., 0.5 = up to 50% of features)

clustering:
  dbscan:
    eps: 20                        # Epsilon for DBSCAN (will be optimized if auto_optimize enabled)
    min_samples: 5                 # Min_samples for DBSCAN (will be optimized if auto_optimize enabled)
    
    # DBSCAN Parameter Optimization
    auto_optimize: True            # Enable automatic parameter optimization
    optimization:
      target_anomaly_rate: 0.05    # Target 5% anomalies
      min_clusters: 2              # Minimum desired clusters
      max_clusters: 15             # Maximum desired clusters  
      n_trials: 25                 # Number of parameter combinations to try
      plot_results: True           # Plot optimization results

bayesian_anomaly_detection:
  enabled: True
  method: "bayesian_network"
  threshold_percentile: 97  
  contamination: 0.02       
  compare_with_dbscan: True